// Single source of truth for "which routes have a generated Markdown twin".
// -----------------------------------------------------------------------------
// Markdown (`<route>.md`) is generated by @signalwire/docusaurus-plugin-llms-txt
// for the en locale only, for the latest doc version (served at /docs/ with no
// version prefix) plus all /releasenotes/ pages.
//
// Three places need to agree on that rule:
//   1. docusaurus.config.js — `markdown.excludeRoutes` / `llmsTxt.excludeRoutes`
//      (what actually gets generated)
//   2. cloudfront/viewer-request-markdown.js — the CloudFront Function that
//      rewrites `Accept: text/markdown` requests to the .md twin. It runs in an
//      isolated runtime and cannot import this file, so it keeps its own copy;
//      scripts/check-cloudfront-excludes.js fails the build if the two drift.
//   3. src/components/MarkdownActions — only shows the "Markdown" control on
//      pages that actually have a twin.
//
// CommonJS so the plain-node check script, the Docusaurus config, and the
// client bundle can all consume it.
// -----------------------------------------------------------------------------

// Route trees with no Markdown at all.
const EXCLUDED_ROUTE_TREES = [
  '/docs/cover_pages/',
  '/docs/category/',
];

// Individual DocCardList-only section index pages (navigation, no content).
// Add new ones here as the nav structure evolves — this is the only list.
const EXCLUDED_ROUTES = [
  '/docs/administration/',
  '/docs/administration/management/',
  '/docs/administration/management/configuration/',
  '/docs/benchmarking/',
  '/docs/data_source/catalog/catalog_intro/',
  '/docs/faq/',
  '/docs/integrations/',
  '/docs/integrations/streaming/',
  '/docs/integrations/streaming/apache_kafka/',
  '/docs/introduction/',
  '/docs/loading/',
  '/docs/loading/loading_introduction/loading_overview/',
  '/docs/loading/objectstorage/',
  '/docs/project_help/',
  '/docs/sql-reference/data-types/',
  '/docs/sql-reference/data-types/date-types/',
  '/docs/sql-reference/sql-functions/',
  '/docs/sql-reference/sql-functions/date-time-functions/',
  '/docs/unloading/',
];

// Glob form consumed by the llms-txt plugin's `excludeRoutes` options.
const EXCLUDE_ROUTE_PATTERNS = [
  // Pure navigation pages — no content for LLMs
  ...EXCLUDED_ROUTE_TREES.map((tree) => `${tree}**`),
  // DocCardList-only section index pages
  ...EXCLUDED_ROUTES,
];

const EXCLUDED_ROUTE_SET = new Set(EXCLUDED_ROUTES);

// Older versions are served at /docs/<major>.<minor>/... and have no .md twin.
const VERSIONED_SEGMENT = /^[0-9]+\.[0-9]+/;

/**
 * Does this page route have a generated `.md` twin?
 *
 * Mirrors `docHasMarkdownTwin()` in cloudfront/viewer-request-markdown.js.
 * Localized routes (/zh/..., /ja/...) return false because they do not start
 * with /docs/ or /releasenotes/.
 *
 * @param {string} pathname e.g. '/docs/quick_start/'
 * @returns {boolean}
 */
function hasMarkdownTwin(pathname) {
  if (!pathname) {
    return false;
  }
  // Normalize to the trailing-slash form the site serves (trailingSlash: true).
  const uri = pathname.endsWith('/') ? pathname : `${pathname}/`;

  // Release notes: every page has a Markdown twin.
  if (uri.startsWith('/releasenotes/')) {
    return true;
  }

  if (!uri.startsWith('/docs/')) {
    return false;
  }

  const afterDocs = uri.substring('/docs/'.length);
  const firstSegment = afterDocs.split('/')[0];

  // '/docs/' root itself has no .md twin.
  if (firstSegment === '') {
    return false;
  }

  if (VERSIONED_SEGMENT.test(firstSegment)) {
    return false;
  }

  if (EXCLUDED_ROUTE_TREES.some((tree) => uri.startsWith(tree))) {
    return false;
  }

  return !EXCLUDED_ROUTE_SET.has(uri);
}

/**
 * The `.md` twin URL for a page route: strip the trailing slash, append '.md'.
 * Does not check existence — call hasMarkdownTwin() first.
 *
 * @param {string} pathname
 * @returns {string}
 */
function markdownUrlFor(pathname) {
  const uri = pathname.endsWith('/') ? pathname.slice(0, -1) : pathname;
  return `${uri}.md`;
}

module.exports = {
  EXCLUDED_ROUTE_TREES,
  EXCLUDED_ROUTES,
  EXCLUDE_ROUTE_PATTERNS,
  hasMarkdownTwin,
  markdownUrlFor,
};
